apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-cm-env
  labels:
    app: helloworld-cm-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-cm-env
  template:
    metadata:
      labels:
        app: helloworld-cm-env
    spec:
      containers:
      - name: helloworld
        image: particule/helloworld
        ports:
        - containerPort: 80
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.level
        - name: LOG_LOCATION
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.location
