apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-cm-vol
  labels:
    app: helloworld-cm-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-cm-vol
  template:
    metadata:
      labels:
        app: helloworld-cm-vol
    spec:
      containers:
      - name: helloworld
        image: particule/helloworld
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: log-config
